### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by minhtrancccp** [minhtrancccp/miscellaneous-python#19]
### Tasks

- [ ] Move README and CODEOWNERS into the `docs` folder
- [ ] Try to put the COPYING file into the `docs` folder as well
- [ ] Add a new CONTRIBUTING file

### References
1. https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors
